
export const profile = {
  name: "Patricia Maureen Tamura-Ramos",
  brand: "Business Operations | AI & Automation",
  headline: "AI Automation Specialist for Business Operations",
  email: "tamurapmj@gmail.com",
  location: "Cavite, Philippines",
  linkedin: "https://www.linkedin.com/in/patricia-maureen-tamura-1b1a061aa/",
  credly: "https://www.credly.com/users/patricia-maureen-tamura",
  calendar: process.env.NEXT_PUBLIC_CALENDAR_URL || "https://calendar.app.google/CYjqArPZVA8cz3Gj8"
};

export const tools = ["Power BI","Excel","Power Automate","Power Apps","Copilot","n8n","Airtable","Buffer","ChatGPT","Claude Code","LinkedIn Sales Navigator","PipeDrive","Google Workspace","SharePoint","GoHighLevel","Zendesk","HubSpot"];

export const projects = [
 {slug:"ai-social-media-content-automation-n8n", featured:true, title:"AI Social Media Content Automation via n8n", image:"/projects/n8n-social-media.png", category:"AI Automation", summary:"End-to-end workflow that turns a client content request into an AI-generated caption, approval email, tracked status update, and Buffer Instagram draft.", problem:"Small business owners struggle to stay consistent because requests, captions, approvals, and scheduling happen in separate places.", solution:"Connected Google Forms, Sheets, n8n, Gemini AI, Gmail, and Buffer to automate request capture, caption drafting, approval tracking, and Buffer draft creation.", impact:"Reduced manual effort from around 20–30 minutes per post to approximately 5–10 minutes per post while keeping human review in place.", workflow:["Google Form","Google Sheets","n8n","Gemini AI","Gmail Approval","Approved Status","Buffer Draft","Tracker Update"], tags:["n8n","Google Forms","Google Sheets","Gemini AI","Gmail","Buffer","API / MCP"]},
 {slug:"cia-copilot-ai-workforce-agent", title:"CIA: Copilot AI Workforce Agent", image:"/projects/cia-copilot-agent.png", category:"Agentic AI", summary:"Agentic AI assistant built with Microsoft Copilot to analyze workforce indicators, generate insights, recommend actions, and compare forecast scenarios.", problem:"Operational teams often need to interpret several workforce and financial indicators before deciding what action to take.", solution:"Built a Copilot-based agent that reads structured data, summarizes current conditions, provides interpretation, and suggests action-based scenarios.", impact:"Improved the speed and consistency of insight generation while keeping sensitive data masked in this public portfolio.", workflow:["Excel Data","Copilot Agent","Business Logic","Insight Summary","Recommended Actions","Forecast Comparison"], tags:["Copilot","AI Agent","Excel Data","Forecasting"]},
 {slug:"analytics-tool-with-automation", title:"Analytics Tool with Automation", image:"/projects/project-analytics-tool-redacted.png", category:"Operations Analytics", summary:"Tool that automates calculations and validations, improving accuracy and reducing manual effort.", problem:"Manual validation and analysis can slow down operations.", solution:"Created a structured analytics tool with automated rules and validation views.", impact:"Converted raw operational inputs into clearer outputs for review and action.", workflow:["Data Input","Validation Rules","Automated Calculations","Summary Output"], tags:["Excel","VBA","Automation"]},
 {slug:"forecasting-dashboard", title:"Forecasting Dashboard", image:"/projects/project-forecast-dashboard-redacted.png", category:"Dashboarding", summary:"Scenario-based dashboard for strategic workforce and profitability planning.", problem:"Leaders need a clear way to compare current state, demand, supply, and projections.", solution:"Designed a dashboard that brings forecasting metrics into a simple decision-ready view.", impact:"Improved visibility for planning conversations and leadership reviews.", workflow:["Data Sources","Forecast Logic","Dashboard View","Leadership Review"], tags:["Power BI","Forecasting","Analytics"]},
 {slug:"asset-verification-automation", title:"Asset Verification Automation", image:"/projects/project-asset-automation-redacted.png", category:"Workflow Automation", summary:"Automated workflow with approval and validation steps to support data accuracy and audit readiness.", problem:"Manual asset checks require repeated follow-ups.", solution:"Used automation to collect responses, track status, and support validation.", impact:"Reduced repetitive follow-ups and improved visibility of completion status.", workflow:["Request","User Validation","Status Tracking","Reminder Flow","Final Tracker"], tags:["Power Automate","Workflow","Validation"]},
 {slug:"compliance-reporting-automation", title:"Compliance & Reporting Automation", image:"/projects/project-reporting-automation-redacted.png", category:"Reporting Automation", summary:"Automated recurring reporting checks, reminders, and gap alerts to improve process discipline.", problem:"Recurring submissions often require manual checking and chasing.", solution:"Built an automated workflow to check status, trigger reminders, and update trackers.", impact:"Improved reporting discipline and reduced repetitive admin effort.", workflow:["Submission Tracker","Status Check","Gap Alert","Reminder","Completion Update"], tags:["Power Automate","Compliance","Alerts"]}
];

export const badges = [
 {title:"Reinvention with Agentic AI", issuer:"Accenture", image:"/badges/agentic-ai.png", link:"https://www.credly.com/badges/2429a2de-b4d9-487b-b668-7e1be89cb3c9/public_url"},
 {title:"Google Data Analytics Professional Certificate", issuer:"Google", image:"/badges/data-analytics.png", link:"https://www.credly.com/badges/ce938e77-52f4-43d4-a693-d47e479aa0ac/public_url"},
 {title:"Google Project Management Professional Certificate", issuer:"Google", image:"/badges/project-management.png", link:"https://www.credly.com/badges/dc7143e1-805f-40f3-92ac-d203b00c1107/public_url"},
 {title:"Lean Six Sigma Yellow Belt", issuer:"Process Improvement", image:"/badges/six-sigma.png", link:"/certificates/Lean-Six-Sigma-Yellow-Belt.pdf"},
 {title:"Agile Scrum, Jira & Confluence", issuer:"Agile Project Management", image:"/badges/agile-scrum.png", link:"/certificates/Agile-Scrum-Jira-Confluence-Certificate.pdf"}
];
